name: Format

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  format:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Lint with Ruff
      run: ruff check --output-format=github .
